<?php

namespace AppBundle\Repository;

/**
 * categoryLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryLivreRepository extends \Doctrine\ORM\EntityRepository
{
}
